# install OpenCV by OS_family
- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

# configure OpenCV

- name: Create opencv User
  user:
    name: opencv
    shell: /usr/sbin/nologin
    home: /data/wwwroot/opencv
    create_home: no

- name: Create opencv directory
  file:
    path: /data/wwwroot/opencv
    state: directory
    owner: opencv
    group: opencv
    
- name: Download opencv
  get_url:
    dest: /data/wwwroot/opencv
    url: "{{opencv_download_url}}"
    owner: opencv
    group: opencv

- name: Set opencv config
  template:
    src: opencv.conf.jinja2
    dest: /data/wwwroot/opencv/opencv.conf
    owner: opencv
    group: opencv

- name: Setting opencv service
  copy:
    src: opencv.service
    dest: /lib/systemd/system/opencv.service

- name: Restart opencv
  service:
    name: opencv.service
    state: restarted
    enabled: yes

- name: Create opencv System User
  user:
      name: opencv 
      create_home: no 
      home: /opt/opencv
      shell: /usr/sbin/nologin

- name: Download opencv
  unarchive:
      src: "{{opencv_download_url}}"
      dest: /opt/ 
      group: opencv 
      remote_src: yes
      owner: opencv
      mode: g+w

- name: Create the storage directory for files.
  file:
      path: /opt/opencv/data
      state: directory 
      owner: opencv 
      group: opencv
      mode: g+w
      
- name: Set database connection /opt/opencv/config/config.json
  lineinfile:
    dest: /opt/opencv/config/config.json
    regexp: '"DataSource":'
    line: '    "DataSource": "{{opencv_db_user}}:{{opencv_db_password}}@tcp(localhost:3306)/{{opencv_db_name}}?charset=utf8mb4,utf8&readTimeout=30s&writeTimeout=30s",'
    backrefs: yes 

# set soft link, -f enforce the exist links
# ln -sf src des
- name: set soft link
  shell: |
    ln -sf /opt/opencv  /data/wwwroot
    ln -sf /opt/opencv/config /data/config

# Check version,
# must use sudo sh -c to solve the no-root permission
- block:
  - name: Check OpenCV Version
    shell: sudo sh -c "opencvctl status | grep 'OpenCV version' 1>> /data/logs/install_version.txt"

  - name: Check Erlang Version
    shell: sudo sh -c 'echo "Erlang $(yum info erlang | grep Version | sed -n 1p)" 1>> /data/logs/install_version.txt'
    when: ansible_os_family=="RedHat"

# check service state
- name: Check OpenCV Service
  shell: systemctl status opencv | grep Active*
  register: check_opencv_service
  notify: check_opencv_service
