# install OpenCV by OS_family
- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

# configure OpenCV


#- name: Install opencv-python  pencv-contrib-python
#  shell: | 
#    pip install opencv-python
#    pip install opencv-contrib-python

# set soft link, -f enforce the exist links
# ln -sf src des
- name: set soft link
  shell: |
    ln -sf /opt/opencv  /data/wwwroot
    ln -sf /opt/opencv/config /data/config

# Check version,
# must use sudo sh -c to solve the no-root permission
- block:
  - name: Check OpenCV Version
    shell: 
      echo `pkg-config --modversion opencv4` >> /data/logs/install_version.txt

  
   


